///////////////////// M E R G E   S O R T ////////////////////////


// DIVIDE AND CONQUER
// STABE ALGO(STABLE MEANS IT MAINTAINS THE ORDER OR ORIGINAL ITEM)
// Theta(N LOG N)-TIME & O(N)-SPACE
// THIS ALGO IS WELL SUITED FOR EXTERNAL SORTING(MEANS WE CAN BRING PARTS OF INPUT TO BE SORTED IN RAM AND SORT THOSE PARTS)