#!/bin/bash
read -r file_name
print_banner() {
    clear
    gum style \
    --border rounded  \
    --bold \
    --border-foreground="#ff3399" \
    --width=3 \
    --padding="0 3" \
"
Console OP : $file_name
"
}

print_banner

g++ "$file_name"
# console op
./a.out < ip.txt

# op.txt output

# ./a.out < ip.txt > op.txt && code op.txt

#debug mode
# ./a.out < ip.txt > op.txt
# ./dbg > debug.txt && code debug.txt